language: go
go_import_path: github.com/da2018/gone
git:
  depth: 1
env:
  - GO111MODULE=on
go: [ 1.11.x, 1.12.x, 1.13.x ]
os: [ linux, osx ]
matrix:
  exclude:
    - go: 1.12.x
      env: GO111MODULE=off
    - go: 1.11.x
      os: osx
install:
  - go mod download
script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -race -v ./...
  - go test -bench . ./...
